### ISSUE TITLE
Error after inserting the login credentials

### ISSUE THREAD

**Issue by kfussmann** [mikey0000/Mammotion-HA#103]
### The problem

On first start of the integration and after tiping all necessary login details the integration shows an error "Account or password mismatch" although all given login details are correct. I have doublechecked both, the email adress as also the password. The error occured with version 0.1.15 as also with the newest version 0.1.18. The logs don't show anything regarding the error message.

![Screenshot 2024-09-02 093713](https://github.com/user-attachments/assets/f472974b-f1d8-4c01-89d9-a4493f1b5d3e)

### What Mammotion mower are you using?

Luba 1

### What version of the Mammotion intergration are you using?

v0.1.18

### What version of Home Assistant Core are you running?

core-2024.8.3

**Comment by mikey0000** [comment]
That error comes directly from mammotion servers. The only way to verify whether it's the integration or a typo would be to try directly from the underlying api library. Can you jump on discord so I can work with you to figure this out. Seems to only happen to some users.

Can you verify that you are using a normal account and not Google or another oauth provider?

**Comment by kfussmann** [comment]
> That error comes directly from mammotion servers. The only way to verify whether it's the integration or a typo would be to try directly from the underlying api library. Can you jump on discord so I can work with you to figure this out. Seems to only happen to some users.
> 
> Can you verify that you are using a normal account and not Google or another oauth provider?

I can jump to dicord if you would be so kind and give me a link to do so as shortcut.

And yes I can verify that I am using a normal, non Google account, to log me in.

**Comment by InToSSH** [comment]
@mikey0000 What are my options when I use the Google account to log in? 

I remember when I registered, it asked me for a password as well and I have it saved in my password manager, so I assumed I would be able to log in both ways, but when I try to log in in the app, it says that account wasn't found. 

I also tried to create a new account using the same email address as google account, that allowed me to log in, but my mower wasn't there and I couldn't even share it from my main (Google auth) account because it said it is the same account lol, not even using the account ID, which is different.

**Comment by mikey0000** [comment]
Try using the account number, but it's best to create a second account on a new email address. Otherwise jump on discord and pm me so we can work out the issue.

**Comment by mikey0000** [comment]
@InToSSH Have you resolved this with the second account?

**Comment by InToSSH** [comment]
@mikey0000 yes I did, thank you.
If anyone wants to do the same, you have to create the other account with email, then delete the app data, because it caches all the logins used and will tell you that you can't share a device with yourself.
So create account with email, login, logout, delete app data, login to your main account  share the device, logout, delete app data, login with email account, accept the new devices, logout, login to main account. Then you can add the email account to HA.
Also don't try to use the + notation in email, it doesn't work, so something like myemail+mammotion@gmail.com
